name: "Rsync Manager"
slug: "rsync_manager"
version: "1.0.44"
description: "Gestion de jobs rsync via UI Ingress"
codenotary: "thibaut.lamoureux@gmail.com"
arch:
  - amd64
startup: services
boot: auto
init: false

ingress: true
ingress_port: 8099
panel_icon: "mdi:folder-sync"
panel_title: "Rsync Manager"

# map:
#  - config:rw    # Les fichiers .yaml, scripts, et bases de données de HA
#  - share:rw     # Le dossier d'échange entre tous les addons
#  - media:rw     # Photos, vidéos et dossiers multimédias
#  - backup:rw    # Les sauvegardes (.tar) créées par HA lui-même
#  - addons:rw    # (Optionnel) Lecture seule pour sauvegarder tes propres configurations d'addons
#  - ssl:rw       # (Optionnel) Pour les certificats si besoin

privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH

apparmor: true

options: {}
schema: {}
