server.document-root = "/www"
server.port = 8099

server.modules += ( "mod_cgi", "mod_setenv" )

setenv.add-response-header = (
    "Cache-Control" => "no-store, no-cache, must-revalidate, max-age=0",
    "Pragma" => "no-cache",
    "Expires" => "0"
)

cgi.assign = ( ".sh" => "/bin/bash" )

index-file.names = ( "index.html" )
